const EXERCISE_DATABASE = [
  // --- CHEST ---
  { name: "Barbell Bench Press", category: "Chest" },
  { name: "Incline Barbell Bench Press", category: "Chest" },
  { name: "Decline Barbell Bench Press", category: "Chest" },
  { name: "Close-Grip Barbell Bench Press", category: "Chest" },
  { name: "Wide-Grip Barbell Bench Press", category: "Chest" },
  { name: "Reverse-Grip Barbell Bench Press", category: "Chest" },
  { name: "Dumbbell Bench Press", category: "Chest" },
  { name: "Incline Dumbbell Bench Press", category: "Chest" },
  { name: "Decline Dumbbell Bench Press", category: "Chest" },
  { name: "Neutral-Grip Dumbbell Press", category: "Chest" },
  { name: "Single-Arm Dumbbell Bench Press", category: "Chest" },
  { name: "Dumbbell Flyes", category: "Chest" },
  { name: "Incline Dumbbell Flyes", category: "Chest" },
  { name: "Decline Dumbbell Flyes", category: "Chest" },
  { name: "Dumbbell Pullover", category: "Chest" },
  { name: "Smith Machine Flat Press", category: "Chest" },
  { name: "Smith Machine Incline Press", category: "Chest" },
  { name: "Smith Machine Decline Press", category: "Chest" },
  { name: "Iso-Lateral Plate-Loaded Flat Press (Hammer Strength)", category: "Chest" },
  { name: "Iso-Lateral Plate-Loaded Incline Press (Hammer Strength)", category: "Chest" },
  { name: "Iso-Lateral Plate-Loaded Decline Press", category: "Chest" },
  { name: "Iso-Lateral Plate-Loaded Wide Chest Press", category: "Chest" },
  { name: "Converging Chest Press Machine (Selectorized)", category: "Chest" },
  { name: "Machine Chest Press (Seated/Standard)", category: "Chest" },
  { name: "Machine Incline Chest Press", category: "Chest" },
  { name: "Machine Decline Chest Press", category: "Chest" },
  { name: "Pec Deck Flye Machine", category: "Chest" },
  { name: "Machine Chest Flye", category: "Chest" },
  { name: "Cable Crossovers (Mid-Chest)", category: "Chest" },
  { name: "High-to-Low Cable Flyes (Lower Chest)", category: "Chest" },
  { name: "Low-to-High Cable Flyes (Upper Chest)", category: "Chest" },
  { name: "Flat Cable Flyes (Bench)", category: "Chest" },
  { name: "Incline Cable Flyes (Bench)", category: "Chest" },
  { name: "Cable Scooped Chest Press", category: "Chest" },
  { name: "Chest Dips", category: "Chest" },
  { name: "Weighted Chest Dips", category: "Chest" },
  { name: "Machine Assisted Chest Dips", category: "Chest" },
  { name: "Standard Push-Ups", category: "Chest" },
  { name: "Weighted Push-Ups", category: "Chest" },
  { name: "Decline Push-Ups (Feet Elevated)", category: "Chest" },
  { name: "Incline Push-Ups (Hands Elevated)", category: "Chest" },
  { name: "Deficit Push-Ups", category: "Chest" },
  { name: "Bench Press", category: "Chest" },
  { name: "Incline Bench Press", category: "Chest" },
  { name: "Decline Bench Press", category: "Chest" },
  { name: "Incline Dumbbell Press", category: "Chest" },
  { name: "Decline Dumbbell Press", category: "Chest" },
  { name: "Push-Ups", category: "Chest" },
  { name: "Incline Push-Ups", category: "Chest" },
  { name: "Decline Push-Ups", category: "Chest" },
  { name: "Cable Crossovers", category: "Chest" },
  { name: "High-to-Low Cable Flyes", category: "Chest" },
  { name: "Low-to-High Cable Flyes", category: "Chest" },
  { name: "Pec Deck", category: "Chest" },
  { name: "Machine Chest Press", category: "Chest" },
  { name: "Machine Incline Press", category: "Chest" },
  { name: "Machine Decline Press", category: "Chest" },
  { name: "Hammer Strength Flat Press", category: "Chest" },
  { name: "Hammer Strength Incline Press", category: "Chest" },

  // --- BACK (LATS, RHOMBOIDS, LOWER BACK) ---
  { name: "Conventional Barbell Deadlift", category: "Back" },
  { name: "Sumo Barbell Deadlift", category: "Back" },
  { name: "Trap Bar Deadlift (Hex Bar)", category: "Back" },
  { name: "Deficit Barbell Deadlift", category: "Back" },
  { name: "Rack Pulls", category: "Back" },
  { name: "Barbell Bent-Over Rows", category: "Back" },
  { name: "Reverse-Grip Barbell Rows", category: "Back" },
  { name: "Pendlay Rows", category: "Back" },
  { name: "Yates Rows", category: "Back" },
  { name: "T-Bar Rows (Barbell Corner)", category: "Back" },
  { name: "T-Bar Machine Rows (Chest Supported)", category: "Back" },
  { name: "Meadows Rows", category: "Back" },
  { name: "Seal Rows (Cambered Bar/Bench)", category: "Back" },
  { name: "Single-Arm Dumbbell Rows", category: "Back" },
  { name: "Chest-Supported Dumbbell Rows", category: "Back" },
  { name: "Incline Dumbbell Row (Bilateral)", category: "Back" },
  { name: "Wide-Grip Lat Pulldown", category: "Back" },
  { name: "Close-Grip Lat Pulldown", category: "Back" },
  { name: "Reverse-Grip Lat Pulldown", category: "Back" },
  { name: "Neutral-Grip (V-Bar) Lat Pulldown", category: "Back" },
  { name: "Single-Arm Cable Lat Pulldown", category: "Back" },
  { name: "Straight-Arm Cable Pullover", category: "Back" },
  { name: "Cable Seated Rows (V-Bar)", category: "Back" },
  { name: "Cable Seated Rows (Wide Bar)", category: "Back" },
  { name: "Single-Arm Cable Seated Rows", category: "Back" },
  { name: "Iso-Lateral Plate-Loaded High Row (Hammer Strength)", category: "Back" },
  { name: "Iso-Lateral Plate-Loaded Mid Row", category: "Back" },
  { name: "Iso-Lateral Plate-Loaded Low Row", category: "Back" },
  { name: "Iso-Lateral Plate-Loaded Front Lat Pulldown", category: "Back" },
  { name: "Diverging Seated Row Machine (Selectorized)", category: "Back" },
  { name: "Machine Pullover (Nautilus/Plate-Loaded)", category: "Back" },
  { name: "Pull-Ups (Pronated Grip)", category: "Back" },
  { name: "Weighted Pull-Ups", category: "Back" },
  { name: "Machine Assisted Pull-Ups", category: "Back" },
  { name: "Chin-Ups (Supinated Grip)", category: "Back" },
  { name: "Neutral-Grip Pull-Ups", category: "Back" },
  { name: "Good Mornings", category: "Back" },
  { name: "Seated Good Mornings", category: "Back" },
  { name: "Back Extensions (45-Degree Hyperextensions)", category: "Back" },
  { name: "Weighted Back Extensions", category: "Back" },
  { name: "Reverse Hyperextensions", category: "Back" },
  { name: "Deadlift", category: "Back" },
  { name: "Barbell Deadlift", category: "Back" },
  { name: "Sumo Deadlift", category: "Back" },
  { name: "Trap Bar Deadlift", category: "Back" },
  { name: "Pull-Ups", category: "Back" },
  { name: "Chin-Ups", category: "Back" },
  { name: "Lat Pulldown", category: "Back" },
  { name: "Barbell Row", category: "Back" },
  { name: "Bent-Over Barbell Row", category: "Back" },
  { name: "Pendlay Row", category: "Back" },
  { name: "Dumbbell Row", category: "Back" },
  { name: "Single-Arm Dumbbell Row", category: "Back" },
  { name: "Seated Cable Row", category: "Back" },
  { name: "T-Bar Row", category: "Back" },
  { name: "Chest-Supported Row", category: "Back" },
  { name: "Meadows Row", category: "Back" },
  { name: "Machine Row", category: "Back" },
  { name: "Hammer Strength Row", category: "Back" },
  { name: "Straight-Arm Pulldown", category: "Back" },
  { name: "Back Extensions", category: "Back" },
  { name: "Hyperextensions", category: "Back" },

  // --- SHOULDERS (DELTOIDS) ---
  { name: "Standing Overhead Barbell Press (Military Press)", category: "Shoulders" },
  { name: "Seated Barbell Overhead Press", category: "Shoulders" },
  { name: "Behind-The-Neck Barbell Press", category: "Shoulders" },
  { name: "Barbell Push Press", category: "Shoulders" },
  { name: "Seated Dumbbell Shoulder Press", category: "Shoulders" },
  { name: "Standing Dumbbell Shoulder Press", category: "Shoulders" },
  { name: "Arnold Press", category: "Shoulders" },
  { name: "Single-Arm Dumbbell Press", category: "Shoulders" },
  { name: "Smith Machine Overhead Press", category: "Shoulders" },
  { name: "Iso-Lateral Plate-Loaded Shoulder Press (Hammer Strength)", category: "Shoulders" },
  { name: "Converging Shoulder Press Machine (Selectorized)", category: "Shoulders" },
  { name: "Multi-Press Shoulder Machine", category: "Shoulders" },
  { name: "Dumbbell Lateral Raises", category: "Shoulders" },
  { name: "Seated Dumbbell Lateral Raises", category: "Shoulders" },
  { name: "Leaning Dumbbell Lateral Raises", category: "Shoulders" },
  { name: "Cable Lateral Raises", category: "Shoulders" },
  { name: "Machine Lateral Raises (Selectorized)", category: "Shoulders" },
  { name: "Barbell Front Raises", category: "Shoulders" },
  { name: "Dumbbell Front Raises", category: "Shoulders" },
  { name: "Cable Front Raises", category: "Shoulders" },
  { name: "Weight Plate Front Raises", category: "Shoulders" },
  { name: "Dumbbell Reverse Flyes (Rear Delts)", category: "Shoulders" },
  { name: "Chest-Supported Dumbbell Reverse Flyes", category: "Shoulders" },
  { name: "Cable Rear Delt Flyes", category: "Shoulders" },
  { name: "Reverse Pec Deck Machine (Rear Delts)", category: "Shoulders" },
  { name: "Cable Face Pulls", category: "Shoulders" },
  { name: "Barbell Upright Rows", category: "Shoulders" },
  { name: "Dumbbell Upright Rows", category: "Shoulders" },
  { name: "Cable Upright Rows", category: "Shoulders" },
  { name: "Smith Machine Upright Rows", category: "Shoulders" },
  { name: "Overhead Press", category: "Shoulders" },
  { name: "Military Press", category: "Shoulders" },
  { name: "Barbell Shoulder Press", category: "Shoulders" },
  { name: "Dumbbell Shoulder Press", category: "Shoulders" },
  { name: "Seated Dumbbell Press", category: "Shoulders" },
  { name: "Push Press", category: "Shoulders" },
  { name: "Lateral Raises", category: "Shoulders" },
  { name: "Machine Lateral Raises", category: "Shoulders" },
  { name: "Front Raises", category: "Shoulders" },
  { name: "Rear Delt Flyes", category: "Shoulders" },
  { name: "Dumbbell Reverse Flyes", category: "Shoulders" },
  { name: "Reverse Pec Deck", category: "Shoulders" },
  { name: "Face Pulls", category: "Shoulders" },
  { name: "Upright Rows", category: "Shoulders" },
  { name: "Smith Machine Shoulder Press", category: "Shoulders" },
  { name: "Machine Shoulder Press", category: "Shoulders" },

  // --- TRAPS ---
  { name: "Barbell Shrugs", category: "Traps" },
  { name: "Behind-The-Back Barbell Shrugs", category: "Traps" },
  { name: "Dumbbell Shrugs", category: "Traps" },
  { name: "Smith Machine Shrugs", category: "Traps" },
  { name: "Cable Shrugs", category: "Traps" },
  { name: "Trap Bar Shrugs", category: "Traps" },
  { name: "Iso-Lateral Plate-Loaded Shrug Machine", category: "Traps" },
  { name: "Selectorized Shrug Machine", category: "Traps" },
  { name: "Farmer's Walk", category: "Traps" },
  { name: "Shrugs", category: "Traps" },

  // --- BICEPS ---
  { name: "Standing Barbell Curls", category: "Biceps" },
  { name: "Wide-Grip Barbell Curls", category: "Biceps" },
  { name: "Close-Grip Barbell Curls", category: "Biceps" },
  { name: "EZ-Bar Curls", category: "Biceps" },
  { name: "Alternating Dumbbell Curls", category: "Biceps" },
  { name: "Bilateral Dumbbell Curls", category: "Biceps" },
  { name: "Incline Seated Dumbbell Curls", category: "Biceps" },
  { name: "Dumbbell Concentration Curls", category: "Biceps" },
  { name: "Dumbbell Spider Curls", category: "Biceps" },
  { name: "Dumbbell Hammer Curls", category: "Biceps" },
  { name: "Cross-Body Dumbbell Hammer Curls", category: "Biceps" },
  { name: "Preacher Curls (EZ-Bar)", category: "Biceps" },
  { name: "Preacher Curls (Dumbbell)", category: "Biceps" },
  { name: "Selectorized Preacher Curl Machine", category: "Biceps" },
  { name: "Plate-Loaded Biceps Curl Machine", category: "Biceps" },
  { name: "Cable Curls (Straight Bar)", category: "Biceps" },
  { name: "Cable Curls (EZ-Bar Attachment)", category: "Biceps" },
  { name: "Cable Rope Hammer Curls", category: "Biceps" },
  { name: "Single-Arm Cable Curls", category: "Biceps" },
  { name: "High Cable Double Biceps Curls", category: "Biceps" },
  { name: "Behind-the-Back Cable Curls", category: "Biceps" },
  { name: "Drag Curls (Barbell/Dumbbell)", category: "Biceps" },
  { name: "Bicep Curls", category: "Biceps" },
  { name: "Barbell Curls", category: "Biceps" },
  { name: "Dumbbell Curls", category: "Biceps" },
  { name: "Hammer Curls", category: "Biceps" },
  { name: "Preacher Curls", category: "Biceps" },
  { name: "EZ-Bar Preacher Curls", category: "Biceps" },
  { name: "Machine Preacher Curls", category: "Biceps" },
  { name: "Concentration Curls", category: "Biceps" },
  { name: "Spider Curls", category: "Biceps" },
  { name: "Cable Curls", category: "Biceps" },
  { name: "Incline Dumbbell Curls", category: "Biceps" },
  { name: "High Cable Curls", category: "Biceps" },
  { name: "Drag Curls", category: "Biceps" },

  // --- TRICEPS ---
  { name: "EZ-Bar Skull Crushers", category: "Triceps" },
  { name: "Dumbbell Skull Crushers", category: "Triceps" },
  { name: "Barbell JM Press", category: "Triceps" },
  { name: "Seated Overhead Dumbbell Extension", category: "Triceps" },
  { name: "Single-Arm Overhead Dumbbell Extension", category: "Triceps" },
  { name: "Overhead EZ-Bar Extension", category: "Triceps" },
  { name: "Triceps Rope Pushdown", category: "Triceps" },
  { name: "Triceps Straight Bar Pushdown", category: "Triceps" },
  { name: "Triceps V-Bar Pushdown", category: "Triceps" },
  { name: "Reverse-Grip Cable Pushdown", category: "Triceps" },
  { name: "Single-Arm Cable Pushdown", category: "Triceps" },
  { name: "Overhead Cable Rope Extension", category: "Triceps" },
  { name: "Single-Arm Overhead Cable Extension", category: "Triceps" },
  { name: "Dumbbell Kickbacks", category: "Triceps" },
  { name: "Cable Kickbacks", category: "Triceps" },
  { name: "Triceps Dips (Parallel Bars)", category: "Triceps" },
  { name: "Weighted Triceps Dips", category: "Triceps" },
  { name: "Bench Dips", category: "Triceps" },
  { name: "Selectorized Triceps Extension Machine", category: "Triceps" },
  { name: "Plate-Loaded Triceps Dip Machine", category: "Triceps" },
  { name: "Diamond Push-Ups", category: "Triceps" },
  { name: "Triceps Extension", category: "Triceps" },
  { name: "Triceps Pushdown", category: "Triceps" },
  { name: "Rope Pushdown", category: "Triceps" },
  { name: "Straight Bar Pushdown", category: "Triceps" },
  { name: "V-Bar Pushdown", category: "Triceps" },
  { name: "Skull Crushers", category: "Triceps" },
  { name: "Overhead Triceps Extension", category: "Triceps" },
  { name: "Dumbbell Overhead Extension", category: "Triceps" },
  { name: "Cable Overhead Extension", category: "Triceps" },
  { name: "Close-Grip Bench Press", category: "Triceps" },
  { name: "Triceps Dips", category: "Triceps" },
  { name: "JM Press", category: "Triceps" },

  // --- FOREARMS & GRIP ---
  { name: "Barbell Reverse Curls", category: "Forearms" },
  { name: "EZ-Bar Reverse Curls", category: "Forearms" },
  { name: "Cable Reverse Curls", category: "Forearms" },
  { name: "Zottman Curls", category: "Forearms" },
  { name: "Barbell Wrist Curls (Seated)", category: "Forearms" },
  { name: "Dumbbell Wrist Curls", category: "Forearms" },
  { name: "Reverse Barbell Wrist Curls", category: "Forearms" },
  { name: "Reverse Dumbbell Wrist Curls", category: "Forearms" },
  { name: "Behind-The-Back Barbell Wrist Curls", category: "Forearms" },
  { name: "Wrist Roller", category: "Forearms" },
  { name: "Dead Hangs (Time)", category: "Forearms" },
  { name: "Plate Pinches (Time)", category: "Forearms" },
  { name: "Reverse Curls", category: "Forearms" },
  { name: "Wrist Curls", category: "Forearms" },
  { name: "Barbell Wrist Curls", category: "Forearms" },
  { name: "Reverse Wrist Curls", category: "Forearms" },
  { name: "Dead Hangs", category: "Forearms" },
  { name: "Farmer's Walk (Grip Focus)", category: "Forearms" },

  // --- QUADS ---
  { name: "Barbell High-Bar Back Squat", category: "Quads" },
  { name: "Barbell Low-Bar Back Squat", category: "Quads" },
  { name: "Barbell Front Squat", category: "Quads" },
  { name: "Safety Squat Bar (SSB) Squats", category: "Quads" },
  { name: "Zercher Squats", category: "Quads" },
  { name: "Box Squats", category: "Quads" },
  { name: "Dumbbell Goblet Squats", category: "Quads" },
  { name: "Kettlebell Goblet Squats", category: "Quads" },
  { name: "Heel-Elevated Goblet Squats (Cyclist Squats)", category: "Quads" },
  { name: "Smith Machine Squats", category: "Quads" },
  { name: "Bulgarian Split Squats (Dumbbell)", category: "Quads" },
  { name: "Bulgarian Split Squats (Barbell)", category: "Quads" },
  { name: "Linear Leg Press (45-Degree)", category: "Quads" },
  { name: "Horizontal Leg Press (Selectorized)", category: "Quads" },
  { name: "Single-Leg Leg Press", category: "Quads" },
  { name: "Hack Squat Machine (Linear/Rails)", category: "Quads" },
  { name: "Hack Squat Machine (Pivot/Leverage)", category: "Quads" },
  { name: "Pendulum Squat Machine", category: "Quads" },
  { name: "V-Squat Machine", category: "Quads" },
  { name: "Belt Squat Machine (Pit Shark)", category: "Quads" },
  { name: "Dumbbell Walking Lunges", category: "Quads" },
  { name: "Barbell Walking Lunges", category: "Quads" },
  { name: "Dumbbell Reverse Lunges", category: "Quads" },
  { name: "Barbell Reverse Lunges", category: "Quads" },
  { name: "Forward Lunges", category: "Quads" },
  { name: "Leg Extension Machine", category: "Quads" },
  { name: "Single-Leg Extension Machine", category: "Quads" },
  { name: "Sissy Squats (Bodyweight)", category: "Quads" },
  { name: "Sissy Squat Machine", category: "Quads" },
  { name: "Dumbbell Step-Ups", category: "Quads" },
  { name: "Squat", category: "Quads" },
  { name: "Barbell Squat", category: "Quads" },
  { name: "Barbell Back Squat", category: "Quads" },
  { name: "Front Squat", category: "Quads" },
  { name: "Leg Press", category: "Quads" },
  { name: "Hack Squat", category: "Quads" },
  { name: "Machine Hack Squat", category: "Quads" },
  { name: "Leg Extension", category: "Quads" },
  { name: "Machine Leg Extension", category: "Quads" },
  { name: "Lunges", category: "Quads" },
  { name: "Walking Lunges", category: "Quads" },
  { name: "Dumbbell Lunges", category: "Quads" },
  { name: "Reverse Lunges", category: "Quads" },
  { name: "Bulgarian Split Squats", category: "Quads" },
  { name: "Goblet Squats", category: "Quads" },
  { name: "Step-Ups", category: "Quads" },
  { name: "Sissy Squats", category: "Quads" },

  // --- HAMSTRINGS ---
  { name: "Romanian Deadlift (RDL)", category: "Hamstrings" },
  { name: "Dumbbell Romanian Deadlift", category: "Hamstrings" },
  { name: "Single-Leg RDL (Dumbbell/Kettlebell)", category: "Hamstrings" },
  { name: "Stiff-Legged Barbell Deadlift", category: "Hamstrings" },
  { name: "Lying Leg Curl Machine", category: "Hamstrings" },
  { name: "Seated Leg Curl Machine", category: "Hamstrings" },
  { name: "Standing Single-Leg Curl Machine", category: "Hamstrings" },
  { name: "Kneeling Single-Leg Curl Machine", category: "Hamstrings" },
  { name: "Dumbbell Leg Curls", category: "Hamstrings" },
  { name: "Glute-Ham Raise (GHR)", category: "Hamstrings" },
  { name: "Nordic Hamstring Curls", category: "Hamstrings" },
  { name: "Cable Pull-Throughs", category: "Hamstrings" },
  { name: "Kettlebell Swings", category: "Hamstrings" },
  { name: "Barbell RDL", category: "Hamstrings" },
  { name: "Dumbbell RDL", category: "Hamstrings" },
  { name: "Stiff-Legged Deadlift", category: "Hamstrings" },
  { name: "Leg Curls", category: "Hamstrings" },
  { name: "Lying Leg Curls", category: "Hamstrings" },
  { name: "Seated Leg Curls", category: "Hamstrings" },
  { name: "Standing Leg Curls", category: "Hamstrings" },

  // --- GLUTES ---
  { name: "Barbell Hip Thrusts", category: "Glutes" },
  { name: "Dumbbell Hip Thrusts", category: "Glutes" },
  { name: "Single-Leg Hip Thrusts", category: "Glutes" },
  { name: "Glute Drive Machine (Plate-Loaded)", category: "Glutes" },
  { name: "Barbell Glute Bridges", category: "Glutes" },
  { name: "Dumbbell Glute Bridges", category: "Glutes" },
  { name: "Cable Glute Kickbacks", category: "Glutes" },
  { name: "Standing Machine Glute Kickbacks", category: "Glutes" },
  { name: "Multi-Hip Machine (Extension)", category: "Glutes" },
  { name: "Seated Hip Abductor Machine (Outer Thigh)", category: "Glutes" },
  { name: "Seated Hip Adductor Machine (Inner Thigh)", category: "Glutes" },
  { name: "Cable Hip Abductions", category: "Glutes" },
  { name: "Deficit Reverse Lunges", category: "Glutes" },
  { name: "Curtsy Lunges", category: "Glutes" },
  { name: "B-Stance RDLs", category: "Glutes" },
  { name: "Hip Thrusts", category: "Glutes" },
  { name: "Machine Hip Thrusts", category: "Glutes" },
  { name: "Glute Bridges", category: "Glutes" },
  { name: "Glute Kickbacks", category: "Glutes" },
  { name: "Hip Abductor Machine", category: "Glutes" },
  { name: "Hip Adductor Machine", category: "Glutes" },

  // --- CALVES ---
  { name: "Standing Barbell Calf Raises", category: "Calves" },
  { name: "Standing Dumbbell Calf Raises", category: "Calves" },
  { name: "Standing Calf Raise Machine", category: "Calves" },
  { name: "Smith Machine Calf Raises", category: "Calves" },
  { name: "Seated Calf Raise Machine", category: "Calves" },
  { name: "Seated Dumbbell Calf Raises", category: "Calves" },
  { name: "Leg Press Calf Raises", category: "Calves" },
  { name: "Donkey Calf Raise Machine", category: "Calves" },
  { name: "Rotary Calf Machine", category: "Calves" },
  { name: "Single-Leg Calf Raises", category: "Calves" },
  { name: "Tibialis Raises", category: "Calves" },
  { name: "Calf Raises", category: "Calves" },
  { name: "Standing Calf Raises", category: "Calves" },
  { name: "Seated Calf Raises", category: "Calves" },
  { name: "Donkey Calf Raises", category: "Calves" },

  // --- CORE & ABS ---
  { name: "Standard Crunches", category: "Core" },
  { name: "Decline Bench Crunches", category: "Core" },
  { name: "Weighted Crunches", category: "Core" },
  { name: "Hanging Leg Raises", category: "Core" },
  { name: "Hanging Knee Raises", category: "Core" },
  { name: "Captain's Chair Leg Raises", category: "Core" },
  { name: "Lying Floor Leg Raises", category: "Core" },
  { name: "Cable Crunches (Kneeling)", category: "Core" },
  { name: "Cable Crunches (Standing)", category: "Core" },
  { name: "Machine Ab Crunches (Selectorized)", category: "Core" },
  { name: "Rotary Torso Machine", category: "Core" },
  { name: "Ab Coaster Machine", category: "Core" },
  { name: "Ab Wheel Rollouts", category: "Core" },
  { name: "Barbell Rollouts", category: "Core" },
  { name: "Plank (Time)", category: "Core" },
  { name: "Weighted Plank (Time)", category: "Core" },
  { name: "Side Planks (Time)", category: "Core" },
  { name: "Russian Twists", category: "Core" },
  { name: "Weighted Russian Twists", category: "Core" },
  { name: "Bicycle Crunches", category: "Core" },
  { name: "V-Ups", category: "Core" },
  { name: "Dragon Flags", category: "Core" },
  { name: "High-to-Low Cable Woodchoppers", category: "Core" },
  { name: "Low-to-High Cable Woodchoppers", category: "Core" },
  { name: "Pallof Press", category: "Core" },
  { name: "Dead Bugs", category: "Core" },
  { name: "Hollow Body Hold (Time)", category: "Core" },
  { name: "L-Sit Hold (Time)", category: "Core" },
  { name: "Crunches", category: "Core" },
  { name: "Sit-Ups", category: "Core" },
  { name: "Decline Crunches", category: "Core" },
  { name: "Cable Crunches", category: "Core" },
  { name: "Leg Raises", category: "Core" },
  { name: "Lying Leg Raises", category: "Core" },
  { name: "Plank", category: "Core" },
  { name: "Side Plank", category: "Core" },
  { name: "Woodchoppers", category: "Core" },

  // --- CARDIO & FULL BODY CONDITIONING ---
  { name: "Treadmill Running", category: "Cardio" },
  { name: "Treadmill Sprints", category: "Cardio" },
  { name: "Stairmaster / Step Machine", category: "Cardio" },
  { name: "Rowing Machine (Erg)", category: "Cardio" },
  { name: "Stationary Cycling", category: "Cardio" },
  { name: "Assault Bike / Air Bike", category: "Cardio" },
  { name: "Elliptical Trainer", category: "Cardio" },
  { name: "SkiErg", category: "Cardio" },
  { name: "Jump Rope", category: "Cardio" },
  { name: "Burpees", category: "Cardio" },
  { name: "Box Jumps", category: "Cardio" },
  { name: "Sled Push", category: "Cardio" },
  { name: "Sled Pull", category: "Cardio" },
  { name: "Battle Ropes", category: "Cardio" },
  { name: "Tire Flips", category: "Cardio" },
  { name: "Medicine Ball Slams", category: "Cardio" },
  { name: "Treadmill", category: "Cardio" },
  { name: "Stairmaster", category: "Cardio" },
  { name: "Elliptical", category: "Cardio" },
  { name: "Stationary Bike", category: "Cardio" },
  { name: "Rowing Machine", category: "Cardio" }
];
